### ISSUE TITLE
Deep nesting (for,if,while)

### ISSUE THREAD

**Issue by bterwijn** [armand-jr/Sonkrag#1]
In random.py zie ik een diepe nesting als in:

for ...
   if ...
      for ...
         if ...
            while ..
                etc...

Probeer dat te voorkomen door de functie op te splitsen in meerdere functies. Dan krijg je een mooiere structuur waar je makkelijker mee kan werken. En je kan die functies ook een mooie naam geven zodat het duidelijker is wat er gebeurt.

**Comment by armand-jr** [comment]
Bedankt voor de feedback! We hebben het veranderd
